services:
  # 1. Налаштування Бекенду вашого дипломного проекту
  - name: luna-shop-backend
    type: web
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: free

  # 2. Налаштування Фронтенду (Vue.js / Vite)
  - name: luna-shop-official
    type: web
    runtime: docker
    rootDir: frontend
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: free